version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/travels_react
    container_name: travels-react-c
    image: travels-react-img
    ports:
      - 3000:3000
    command: npm start
    environment:
      - WACTHPACK_POLLING=true
